import { useLocation, useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Sparkles } from "lucide-react";

const SolutionResult = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { solution } = location.state || { solution: "No solution generated." };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-7xl mx-auto px-6 py-12">
        <button
          onClick={() => navigate("/task/urgent-legal-filings/select-solution")}
          className="flex items-center gap-2 text-foreground hover:text-muted-foreground transition-colors mb-12"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Selection</span>
        </button>

        <div className="mb-12">
          <div className="flex items-center gap-4 mb-6">
            <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 flex items-center justify-center">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-4xl font-heading font-light text-foreground">AI Generated Solution</h2>
            </div>
          </div>
          <p className="text-muted-foreground text-lg leading-relaxed max-w-4xl">
            Here is the solution generated by the AI based on your prompt.
          </p>
        </div>

        <div className="border border-border bg-card p-8 rounded-lg max-w-4xl">
          <div className="prose prose-invert max-w-none">
            <div className="text-foreground whitespace-pre-wrap leading-relaxed">
              {solution}
            </div>
          </div>
          
          <div className="mt-8 flex gap-4">
            <Button
              onClick={() => navigate("/")}
              variant="outline"
            >
              Return Home
            </Button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default SolutionResult;
